### ISSUE TITLE
Add capability for image manipulation (i.e. e.g. flipping and blur effects).

### ISSUE THREAD

**Issue by mheckner** [OTHRegensburgMedieninformatik/SPL-for-C#13]
These slides show the possibilities created by adding image manipulation:
http://stanford.edu/class/archive/cs/cs106a/cs106a.1164/handouts/Yeah-imageshop.pdf

Details to be discussed... :)

**Comment by mheckner** [comment]
[OOP_SS13_Aufg_Ueb_09_Arrays_ArrayList.pdf](https://github.com/OTHRegensburgMedieninformatik/SPL-for-C/files/4169494/OOP_SS13_Aufg_Ueb_09_Arrays_ArrayList.pdf)
[OOP_SS13_Aufg_Ueb_09_Arrays_und_ArrayList.pdf](https://github.com/OTHRegensburgMedieninformatik/SPL-for-C/files/4169496/OOP_SS13_Aufg_Ueb_09_Arrays_und_ArrayList.pdf)

**Comment by hendrikboeck** [comment]
Interprocess communication through shared memory could be utilized. The procedure has not the same clutter, that occurs when big chunks of data are sent through a pipe. The main problem that arises is that the program has to detect its operating system because shared memory is handled very differently in Windows.

**Includes for UNIX:**
```C
#include <sys/ipc.h>
#include <sys/shm.h>
```

**Includes for WINDOWS:**
```C
#include <windows.h>
```

**Comment by hendrikboeck** [comment]
Found a possibly better solution. I am now using the [ZeroMQ](https://zeromq.org/)-library for communication between the processes. More specifically the TCP protocol is used to send the data between Java and C. Furthermore is the socket platform-independent and open-source. If the library can deliver the necessary throughput, required by the project, is yet to be seen. Nevertheless, first tests look promising.

**Next steps are:**

- developing a socket for ZeroMQ-communication for Java - [Documentation for JeroMQ](https://www.javadoc.io/doc/org.zeromq/jeromq)
- developing a socket for ZeroMQ-communication for C - [Documentation for libzmq](http://api.zeromq.org/)
- developing a format for fast array-transfer

**Test results**

- Sending 100.000 times _"Hello"_ to Java and responding 100.000 with _"Hello, world!"_ to C took ~4s
- Sending an int-Array with 1.000.000 Elements took to short to measure.

**Comment by hendrikboeck** [comment]
> Interprocess communication through shared memory could be utilized. The procedure has not the same clutter, that occurs when big chunks of data are sent through a pipe. The main problem that arises is that the program has to detect its operating system because shared memory is handled very differently in Windows
> ... 
> *- Post from hendrikboeck from 08.02.2020*

Further development of the shared memory has been scrapped, due to incompatibility between memory management of C and Java.

**Comment by mheckner** [comment]
Extend `gobjects.h` by the following functions and implement the changes in `gobjects.c`. Furthermore the ZeroMQ-interface has to be implemented and declared inside the project (in `Java` and `C`).

```C
GImage newGImageFromPixelArray(int **pixels);

int createRGBPixel(int red, int green, int blue);
int createRGBPixel(int red, int green, int blue, int alpha);
int getAlpha(int pixel);
int getBlue(int pixel);
int getGreen(int pixel);
int getRed(int pixel);
int **getPixelArray(GImage img);

void setPixelArray(GImage img, int **pixels);
```

**Comment by hendrikboeck** [comment]
Image manipulation is finally fully working. Cleaning up the code and then pushing it to review. Tests on CMake still pending. 

**Ouput of Example `FlipImage`:**

![flipped](https://user-images.githubusercontent.com/31034824/76954737-238c9e00-6911-11ea-8b3f-981f168a42da.png)

**Comment by hendrikboeck** [comment]
Image manipulation is finally fully working. Cleaning up the code and then pushing it to review. Tests for CMake-Builds were successful apart from the Windows-Test, which has Problems with the ZeroMQ-Library given. Furthermore, I fixed a random bug, which made it only possible to use the ZeroMQ-Pipe once and then it would block all incoming requests. 

The Image bellow showcases all image rotations and flip mechanism possible. (Everything created inside the SPL-engine with a termination time of ~4s)

**Output of Example `FlipImage`:**

![flipped2](https://user-images.githubusercontent.com/31034824/77096856-3934bd00-6a10-11ea-9ec8-cfd8cded0b69.png)

**Comment by hendrikboeck** [comment]
Pixel manipulation is fully functional and working as intended. Furthermore, have I made some improvements to the ZeroMQ-Interface behavior and added a self-diagnosing mode if ports are occupied. The Interface is then switching to unoccupied Ports (necessary if more than one window is opened).

The Image bellow showcases all pixel manipulations possible. (Everything created inside the SPL-engine with a termination time of ~3s)

**Output of Example `FilterImage`:**

![filter](https://user-images.githubusercontent.com/31034824/77190259-3782fc00-6ad9-11ea-8d06-c644500eed0c.png)
